### ISSUE TITLE
The API response is HTML

### ISSUE THREAD

**Issue by maheshm** [tejasbubane/url-shortner#1]
JSON expected

**Comment by tejasbubane** [comment]
Sending in a request header `Accept: application/json` brings in a JSON response from heroku.
I have already mentioned this in the [README](https://github.com/tejasbubane/url-shortner/blob/master/README.md).

However, this is not required on my localhost. (I even tried running in production environment).

**Comment by maheshm** [comment]
Ah. My bad. I was setting content-type to application/json and not the Accept
